#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#



---


- name: Create VM if not exists
  tags: create
  when: "vm_name not in existing_vms.list_vms"
  block:
    - name: Copy the disk configuration script
      copy:
        content: "{{ lookup('file', 'create-config-drive.sh') }}"
        dest: /tmp/create-config-drive.sh
        mode: 0750
      tags:
        - create

    - name: Download base image
      get_url:
        url: "{{ base_image_url}}"
        dest: "/tmp/{{ base_image_name }}"

    - name: Copy base image to libvirt directory
      shell: |
        qemu-img create -f qcow2 {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 {{ vm_disk_gb }}G
        dd if=/tmp/{{ base_image_name }} of={{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 conv=fsync
        qemu-img resize {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 {{ vm_disk_gb }}G
      register: copy_results


    - name: Add SSH key
      set_fact:
        user_ssh_key: "{{ lookup('file', 'id_rsa.pub') }}"

    - name: Copy the vendor configuration
      copy:
        content: "{{ lookup('template', 'vendor-data.yml.j2') }}"
        dest: /tmp/vendor-data-{{ vm_name }}.yml
        mode: 0660

    - name : Configure the image (cloud-init)
      command: |
        /tmp/create-config-drive.sh \
        --ssh-key "{{ lookup('file', 'id_rsa.pub') }}" \
        --vendor-data /tmp/vendor-data-{{ vm_name }}.yml \
        {{ libvirt_pool_dir }}/{{ vm_name }}.iso
      when: copy_results is changed

    # - name: Configure the image
    #   command: |
    #     virt-customize -a {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 \
    #     --hostname {{ vm_name }} \
    #     --root-password password:{{ vm_root_pass }} \
    #     --ssh-inject 'root:string:{{ lookup('file', 'id_rsa.pub') }}'
    #   when: copy_results is changed

    - name: Define VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'vm-template.xml.j2') }}"

    - name: Ensure VM is started
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running
      register: vm_start_result
      until: "vm_start_result is success"
      retries: 15
      delay: 2

    - name: Ensure vendor file is deleted
      file:
        path: "/tmp/vendor-data-{{ vm_name }}.yml"
        state: absent

    - name: Ensure temporary file is deleted
      file:
        path: "/tmp/{{ base_image_name }}"
        state: absent
      when: cleanup_tmp | bool

