
#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#



---

- name: Delete VM if exists
  when: "vm_name in existing_vms.list_vms"
  tags:
    - delete
  block:

    - name: Destroy VM
      community.libvirt.virt:
        command: destroy
        name: "{{ vm_name }}"

    - name: Undefine VM
      community.libvirt.virt:
        command: undefine
        name: "{{ vm_name }}"

    - name: Remove Disk
      file:
        path: "{{ libvirt_pool_dir }}/{{ vm_name }}.qcow2"
        state: absent


    - name: Remove cloud-init iso
      file:
        path: "{{ libvirt_pool_dir }}/{{ vm_name }}.iso"
        state: absent

