---
# tasks file for kvm_provision


- include_tasks: 01_checks.yml
  tags:
    - create
    - delete

- include_tasks: 02_create.yml
  tags:
    - create

- include_tasks: 03_delete.yml
  tags:
    - delete