---
- name: Install and configure zenoh
  hosts: "{{ host | default('zenoh') }}"
  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install prerequisites
      become: true
      apt:
        pkg:
          - build-essential
          - clang
          - libclang-dev
          - git

    - name: check if cargo is installed
      shell: |
        export HOME=/root/
        . /root/.profile
        command -v cargo
      args:
        executable: /bin/bash
      register: cargo_exists
      ignore_errors: yes

    - name: Download rust installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: '0755'
        force: 'yes'


    - name: Install rust toolchain
      when: cargo_exists is failed
      shell: /tmp/rustup.sh -y
      args:
        executable: /bin/bash

    - name: checkout zenoh
      git:
        repo: https://github.com/eclipse-zenoh/zenoh
        dest: /root/zenoh

    - name: Check zenoh
      shell: |
        export HOME=/root/ && . /root/.profile && cd /root/zenoh && cargo fmt --check
      args:
        executable: /bin/bash

    - name: Clippy zenoh
      shell: |
        export HOME=/root/
        . /root/.profile
        cd /root/zenoh
        cargo clippy --all-targets -- -D warnings
      args:
        executable: /bin/bash

    - name: Build zenoh
      shell: |
        export HOME=/root/
        . /root/.profile
        cd /root/zenoh
        cargo build --all-targets
      args:
        executable: /bin/bash

    - name: Test zenoh
      shell: |
        export HOME=/root/
        . /root/.profile
        cd /root/zenoh
        cargo test
        cargo test --doc
      args:
        executable: /bin/bash

    - name: zenoh clean up
      shell: |
        export HOME=/root/
        . /root/.profile
        cd /root/zenoh
        cargo clean
      args:
        executable: /bin/bash