#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#



- name: Manage networking interfaces
  hosts: "{{ host | default('localhost') }}"
  become: true
  vars:
      vlid: 10
      vxlid: 100
      master_face: "{{ ansible_default_ipv4.interface }}"
  tasks:
   - name: network provision role
     include_role:
        name: net_provision
     tags:
        - always
     vars:
         vlan_id: "{{ vlid }}"
         vxlan_id: "{{ vxlid }}"
         master: "{{ master_face }}"