#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#



---

- name: Checks if Requirements are in place
  tags:
    - create
    - delete
    - net_create
    - net_delete

  block:
    - name: Ensure requirements in place
      debug:
        msg: "TODO: requirements check"

    - name: Get Container list
      debug:
        msg: "TODO: get container list"

    - name: Get Networks list
      debug:
        msg: "TODO: get networks list"