---
# defaults file for kvm_provision
base_image_name: jammy-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/{{ base_image_name }}
#base_image_sha: b9b621b26725ba95442d9a56cbaa054784e0779a9522ec6eafff07c6e6f717ea
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: ubu22-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_disk_gb: 10
vm_net: default
vm_root_pass: ato
vm_user: ato
vm_user_pass:  ato
vm_vnc_port: 5900
vm_vnc_autoport: yes
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub