#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#



---
# defaults file for kvm_provision
base_image_name: jammy-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/{{ base_image_name }}
#base_image_sha: b9b621b26725ba95442d9a56cbaa054784e0779a9522ec6eafff07c6e6f717ea
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: ubu22-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_disk_gb: 10
vm_nets:
  - default
vm_root_pass: ato
vm_user: ato
vm_user_pass:  ato
vm_vnc_port: 5900
vm_vnc_autoport: yes
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
# devices are used to for PCIe passthrough, the machine need to be configured
devices: []
  # - bus_id: c6
  #   slot: 00
  #   function: 0
  # - bus_id: c6
  #   slot: 00
  #   function: 1

# defaults for network provision
net_name: dev
net_gw_addr: 192.168.10.1
net_mask: 255.255.255.0
net_dhcp_start: 192.168.10.2
net_dhcp_end: 192.168.10.254