#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#

---

- name: Create Bridge interface
  become_user: root
  become: true
  command: "ip link add {{ br_name }} type bridge"
  when: "br_name is defined and br_name != ''"
  tags:
    - bridge-create


- include_tasks: 00_ifaces.yml
  tags: iface-up
    vars:
      iface: "{{ br_name }}"

- name: Delete Bridge interface
  become_user: root
  become: true
  command: "ip link del {{ br_name }}"
  when: "br_name is defined and br_name != ''"
  tags:
    - bridge-delete


