#
# Copyright (c) 2022 Gabriele Baldoni
#
# This program and the accompanying materials are made available under the
# Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   Gabriele Baldoni, <gabriele@zettascale.tech>
#


---
# tasks file for net_provision

- include_tasks: 01_vlan.yml
  tags:
    - vlan-create
    - vlan-delete